import Head from "next/head";
import Image from "next/image";
import { Barlow_Semi_Condensed } from "next/font/google";

const BarlowSemiBold = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
});

import { Header } from "@/components/Header";
import { CurriculumVitae } from "@/components/CurriculumVitae";
import { AboutMe } from "@/components/AboutMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sadrak Morais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <section id="container-global">
        <Header
          logoDevName="SadrakMorais"
          email="sadraksdk1@gmail.com"
          linkGithub="https://github.com/sadrakmorais"
          githubUser="sadrakmorais"
        />
        <CurriculumVitae
          nameFile="CV - Sadrak Morais.pdf"
          pathFile="assets/my-cv.pdf"
        />
        <AboutMe />
      </section>
    </>
  );
}
